### ISSUE TITLE
Small Typo in readme

### ISSUE THREAD

**Issue by a8underscore** [crimist/trakx#37]
it says under the install section
> git clone github.com/crimist/trakx
but this results in 
> arcticvps ~ # git clone github.com/crimist/trakx
> fatal: repository 'github.com/crimist/trakx' does not exist

the correct text is 
> git clone https://github.com/crimist/trakx

Thanks

**Comment by crimist** [comment]
Thanks for letting me know. Feel free to open an issue/PR for anything you find.
