### ISSUE TITLE
Feature: Serve files over HTTP server

### ISSUE THREAD

**Issue by a8underscore** [crimist/trakx#38]
under
> Modifying HTML pages / default config

it describes how to edit the HTML pages, how would I add a .js file? i tried adding it to the ./trakx/embedded folder and doing 
statik -src embedded/ -include "*.html,*.yaml,*.js" -f -dest embedded/

but when running the tracker, my file responds a 404

**Comment by crimist** [comment]
Trakx doesn't currently support any routes outside of `/`, `/dmca`, `/stats`, `/scape`, and `/announce`.

https://github.com/crimist/trakx/blob/master/tracker/http/worker.go#L76
https://github.com/crimist/trakx/blob/master/tracker/tracker.go#L73

I'll look into adding dynamic routing based on what's in the statik file system.

* Is it possible?
  * For http tracker iterate through filesystem and create map of filename -> contents.
    * Benchmark vs. switch statement. Likely very minor performance impact as map can be cached.
  * Not sure how to do it with http mux.

**Comment by a8underscore** [comment]
Thank you!

**Comment by crimist** [comment]
I've been super busy but I'm aiming to get

**Comment by a8underscore** [comment]
thank you so much man! i really appreciate the work you're putting into this project

**Comment by crimist** [comment]
Thanks! It's been fun to see it grow from barely handing 50req/s to handling thousands with more features.

I've added dynamic HTTP file support to the branch `dynamic-http-file-support` - feel free to give it a test and let me know if that's what you wanted.

Updated `README`:

> ### Modifying default config & HTML pages

> You can modify the default config and pages served by the HTML server by editing/adding them in the `tracker/config/embeded/` folder.

> **WARNING:** Due to the performance focused implementation trakx will only serve files at their full path. Example: `dmca` will 404, `dmca.html` will 200.

**Comment by a8underscore** [comment]
hey, thank you, ill be able to test it soon

**Comment by crimist** [comment]
Did some more testing, performance is good and feature seems complete. Lmk if there's any more changes you think would be useful.

Merged to master.
