### ISSUE TITLE
Feature: IPv6 support

### ISSUE THREAD

**Issue by a8underscore** [crimist/trakx#39]
I think this could be considered a low priority feature

**Comment by crimist** [comment]
Agree, I think it's mostly a matter of modifying the parser to support IPv6.

**Comment by crimist** [comment]
New [netip](https://pkg.go.dev/net/netip) package introduced in 1.18 might help with the IPv6 transition. Uses uint128 internally so may have some performance advantaged as well. Worth benchmarking.

**Comment by crimist** [comment]
Preliminary benchmarks show overall similar cpu performance.

Tasks:
* Upgrade `Peer.IP` to `netip.Addr`
* Upgrade conndb `connAddr` to `netip.AddrPort`
* Bonus: Refactor configuration file format.

**Comment by crimist** [comment]
That should do it on the code side. I've written tests but feel free to try it for yourself and report any issues you find.

I'll leave this ticket open as a reminder to enable and configure IPv6 on the oracle instances to deploy it in production.

**Comment by crimist** [comment]
Instances are up!

* `udp://u6.trakx.crim.ist:1337/` 
* `http://h6.trakx.crim.ist/announce`
